version: '3'
services:
  server:
    image: caddy/caddy:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./caddy/certs:/etc/caddy/certs
      - ./caddy/Caddyfile:/etc/caddy/Caddyfile
      - ./caddy/logs:/etc/caddy/logs
      - ./site_output:/usr/share/caddy/site
  api:
    build:
      context: ./
      dockerfile: ./api/Dockerfile
    ports:
      - "3000:3000"
    env_file:
      - api_env.env
    environment:
      - APP=api
  site:
    image: jojomi/hugo:latest
    volumes:
      - ./site/:/src
      - ./site_output/:/output
    restart: always
    ports:
      - "1313:1313"
    environment:
      - HUGO_BASEURL=https://jackreid.xyz
      - HUGO_THEME=jackreid
  log_upload:
    build:
      context: ./
      dockerfile: ./scripts/logs/Dockerfile
    volumes:
      - ./caddy/logs:/logs
  books_update:
    build:
      context: ./
      dockerfile: ./scripts/books/Dockerfile
    env_file:
      - api_env.env
    environment:
      - APP=books_update
  pocket_update:
    build:
      context: ./
      dockerfile: ./scripts/pocket/Dockerfile
    env_file:
      - api_env.env
    environment:
      - APP=pocket_update
  films_update:
    build:
      context: ./
      dockerfile: ./scripts/films/Dockerfile
    env_file:
      - api_env.env
    environment:
      - APP=films_update
  articles_update:
    build:
      context: ./
      dockerfile: ./scripts/articles/Dockerfile
    env_file:
      - api_env.env
    environment:
      - APP=articles_update
