version: '3'
services:
  server:
    image: caddy/caddy:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./caddy/index.html:/usr/share/caddy/index.html
      - ./caddy/certs:/etc/caddy/certs
      - ./caddy/Caddyfile:/etc/caddy/Caddyfile
  api:
    build:
      context: ./
      dockerfile: ./api/Dockerfile
    ports:
      - "3000:3000"
    env_file:
      - api_env.env
    environment:
      - APP=api
  site:
    image: dceoy/hugo
    command: "server --bind=0.0.0.0 --ignoreCache /"
    working_dir: /site
    ports:
      - "1313:1313"
    volumes:
      - ./site:/site
  grafana:
    image: grafana/grafana
    ports:
    - "3001:3000"
  prometheus:
    image: prom/prometheus
    ports:
    - "9090:9090"
    volumes:
      - ./prometheus/config.yml:/etc/prometheus/prometheus.yml
  books_update:
    build:
      context: ./
      dockerfile: ./scripts/books/Dockerfile
    env_file:
      - api_env.env
    environment:
      - APP=books_update
  pocket_update:
    build:
      context: ./
      dockerfile: ./scripts/pocket/Dockerfile
    env_file:
      - api_env.env
    environment:
      - APP=pocket_update
  films_update:
    build:
      context: ./
      dockerfile: ./scripts/films/Dockerfile
    env_file:
      - api_env.env
    environment:
      - APP=films_update
  articles_update:
    build:
      context: ./
      dockerfile: ./scripts/articles/Dockerfile
    env_file:
      - api_env.env
    environment:
      - APP=articles_update
