global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: david
    static_configs:
    - targets: ['localhost:9090']

  - job_name: api
    static_configs:
    - targets: ['api:3000']

